<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_68c99054256d6',
	'title' => 'Restaurantes',
	'fields' => array(
		array(
			'key' => 'field_68c9905426aa1',
			'label' => 'Limbo Tribunal',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c991880f705',
			'label' => 'Limbo Tribunal',
			'name' => 'limbotribunal',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68c9905426992',
					'label' => 'Dirección',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => 'C. de San Mateo, 3, Centro, 28004 Madrid',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c99054269cb',
					'label' => 'Teléfono',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '+34 919 01 47 60',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c991d10f706',
					'label' => 'Horario',
					'name' => 'opening_hours',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => 5,
					'placeholder' => 'D-X: 8:00 – 0:30 J: 8:00 – 1:00 V-S: 8:00 – 2:00',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_68c9905426adb',
					'label' => 'Desayunos',
					'name' => 'url_breakfast',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9905426b14',
					'label' => 'Carta',
					'name' => 'url_menu',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9905426b4d',
					'label' => 'Bebidas',
					'name' => 'url_drinks',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9905426b87',
					'label' => 'Postres',
					'name' => 'url_dessert',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9905426bfb',
					'label' => 'Plato de la semana',
					'name' => 'url_dish_week',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9905426bc1',
					'label' => 'Take away',
					'name' => 'url_take_away',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9a0539e498',
					'label' => 'Reserva',
					'name' => 'url_booking',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_68c9922a67b88',
			'label' => 'Ojalá Beach Bar',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c9922f67b89',
			'label' => 'Ojalá Beach Bar',
			'name' => 'ojalabeachbar',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68c9922f67b8a',
					'label' => 'Dirección',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => 'C. de San Mateo, 3, Centro, 28004 Madrid',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9922f67b8b',
					'label' => 'Teléfono',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '+34 919 01 47 60',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9922f67b8c',
					'label' => 'Horario',
					'name' => 'opening_hours',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => 5,
					'placeholder' => 'D-X: 8:00 – 0:30 J: 8:00 – 1:00 V-S: 8:00 – 2:00',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_68c9922f67b8d',
					'label' => 'Desayunos/Brunch',
					'name' => 'url_breakfast',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9922f67b8e',
					'label' => 'Carta',
					'name' => 'url_menu',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9922f67b8f',
					'label' => 'Bebidas',
					'name' => 'url_drinks',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9922f67b90',
					'label' => 'Cócteles',
					'name' => 'url_cocktails',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9922f67b91',
					'label' => 'Take away',
					'name' => 'url_take_away',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9a0619e499',
					'label' => 'Reserva',
					'name' => 'url_booking',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_68c992c867b9f',
			'label' => 'Ojalá Pool Bar',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c992d667ba0',
			'label' => 'Ojalá Pool Bar',
			'name' => 'ojalapoolbar',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68c992d667ba1',
					'label' => 'Dirección',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => 'C. de San Mateo, 3, Centro, 28004 Madrid',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c992d667ba2',
					'label' => 'Teléfono',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '+34 919 01 47 60',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c992d667ba3',
					'label' => 'Horario',
					'name' => 'opening_hours',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => 5,
					'placeholder' => 'D-X: 8:00 – 0:30 J: 8:00 – 1:00 V-S: 8:00 – 2:00',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_68c992d667ba4',
					'label' => 'Desayunos/Brunch',
					'name' => 'url_breakfast',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c992d667ba5',
					'label' => 'Carta',
					'name' => 'url_menu',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c992d667ba6',
					'label' => 'Bebidas',
					'name' => 'url_drinks',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c992d667ba7',
					'label' => 'Cócteles',
					'name' => 'url_cocktails',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c992d667ba8',
					'label' => 'Take away',
					'name' => 'url_take_away',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9a06b9e49a',
					'label' => 'Reserva',
					'name' => 'url_booking',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_68c992f867ba9',
			'label' => 'Cafetería HD',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c9930467baa',
			'label' => 'Cafetería HD',
			'name' => 'cafeteriahd',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68c9930467bab',
					'label' => 'Dirección',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => 'C. de San Mateo, 3, Centro, 28004 Madrid',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9930467bac',
					'label' => 'Teléfono',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '+34 919 01 47 60',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9930467bad',
					'label' => 'Horario',
					'name' => 'opening_hours',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => 5,
					'placeholder' => 'D-X: 8:00 – 0:30 J: 8:00 – 1:00 V-S: 8:00 – 2:00',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_68c9930467bae',
					'label' => 'Desayunos/Brunch',
					'name' => 'url_breakfast',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9930467baf',
					'label' => 'Carta',
					'name' => 'url_menu',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9930467bb0',
					'label' => 'Bebidas',
					'name' => 'url_drinks',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9930467bb1',
					'label' => 'Cócteles/Aperitivos',
					'name' => 'url_cocktails',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9930467bb2',
					'label' => 'Take away',
					'name' => 'url_take_away',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9a0729e49b',
					'label' => 'Reserva',
					'name' => 'url_booking',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_68c9933367bb3',
			'label' => 'Musa Malasaña',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c9934367bb4',
			'label' => 'Musa Malasaña',
			'name' => 'musamalasana',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68c9934367bb5',
					'label' => 'Dirección',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => 'C. de San Mateo, 3, Centro, 28004 Madrid',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9934367bb6',
					'label' => 'Teléfono',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '+34 919 01 47 60',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9934367bb7',
					'label' => 'Horario',
					'name' => 'opening_hours',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => 5,
					'placeholder' => 'D-X: 8:00 – 0:30 J: 8:00 – 1:00 V-S: 8:00 – 2:00',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_68c9934367bb8',
					'label' => 'Desayunos',
					'name' => 'url_breakfast',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9934367bb9',
					'label' => 'Carta',
					'name' => 'url_menu',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9934367bba',
					'label' => 'Bebidas',
					'name' => 'url_drinks',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9934367bbb',
					'label' => 'Postres',
					'name' => 'url_dessert',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9934367bbc',
					'label' => 'Take away',
					'name' => 'url_take_away',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9a07a9e49c',
					'label' => 'Reserva',
					'name' => 'url_booking',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_68c9938267bbd',
			'label' => 'Musa Latina',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c9938a67bbe',
			'label' => 'Musa Latina',
			'name' => 'musalatina',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68c9938a67bbf',
					'label' => 'Dirección',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => 'C. de San Mateo, 3, Centro, 28004 Madrid',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9938a67bc0',
					'label' => 'Teléfono',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '+34 919 01 47 60',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9938a67bc1',
					'label' => 'Horario',
					'name' => 'opening_hours',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => 5,
					'placeholder' => 'D-X: 8:00 – 0:30 J: 8:00 – 1:00 V-S: 8:00 – 2:00',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_68c9938a67bc2',
					'label' => 'Desayunos/Brunch',
					'name' => 'url_breakfast',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9938a67bc3',
					'label' => 'Carta',
					'name' => 'url_menu',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9938a67bc4',
					'label' => 'Bebidas',
					'name' => 'url_drinks',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9938a67bc5',
					'label' => 'Postres',
					'name' => 'url_dessert',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9938a67bc6',
					'label' => 'Take away',
					'name' => 'url_take_away',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9a0829e49d',
					'label' => 'Reserva',
					'name' => 'url_booking',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_68c993a767bc7',
			'label' => 'Run, Run, Run',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c993b567bc8',
			'label' => 'Run, Run, Run',
			'name' => 'runrunrun',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68c993b567bc9',
					'label' => 'Dirección',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => 'C. de San Mateo, 3, Centro, 28004 Madrid',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c993b567bca',
					'label' => 'Teléfono',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '+34 919 01 47 60',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c993b567bcb',
					'label' => 'Horario',
					'name' => 'opening_hours',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => 5,
					'placeholder' => 'D-X: 8:00 – 0:30 J: 8:00 – 1:00 V-S: 8:00 – 2:00',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_68c993b567bcc',
					'label' => 'Desayunos/Brunch',
					'name' => 'url_breakfast',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c993b567bcf',
					'label' => 'Postre/Obrador',
					'name' => 'url_dessert',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c993b567bce',
					'label' => 'Bebidas',
					'name' => 'url_drinks',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9940167bd1',
					'label' => 'Run, Run, Run Nights',
					'name' => 'url_nights',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c993b567bcd',
					'label' => 'Carta',
					'name' => 'url_menu',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c993b567bd0',
					'label' => 'Take away',
					'name' => 'url_take_away',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9a08b9e49e',
					'label' => 'Reserva',
					'name' => 'url_booking',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_68c9942a67bd2',
			'label' => 'Sound Baths',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c9943367bd3',
			'label' => 'Sound Baths',
			'name' => 'soundbaths',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68c9943367bd4',
					'label' => 'Dirección',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => 'C. de San Mateo, 3, Centro, 28004 Madrid',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9943367bd5',
					'label' => 'Teléfono',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '+34 919 01 47 60',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9943367bd6',
					'label' => 'Horario',
					'name' => 'opening_hours',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => 5,
					'placeholder' => 'D-X: 8:00 – 0:30 J: 8:00 – 1:00 V-S: 8:00 – 2:00',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_68c9943367bdb',
					'label' => 'DJ\'s & Program',
					'name' => 'url_djs_program',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9943367bdc',
					'label' => 'About',
					'name' => 'url_about',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9a0939e49f',
					'label' => 'Reserva',
					'name' => 'url_booking',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_68c9948467bdd',
			'label' => 'Down Stairs',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c9948f67bde',
			'label' => 'Down Stairs',
			'name' => 'downstairs',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_68c9948f67bdf',
					'label' => 'Dirección',
					'name' => 'address',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => 'C. de San Mateo, 3, Centro, 28004 Madrid',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9948f67be0',
					'label' => 'Teléfono',
					'name' => 'phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '+34 919 01 47 60',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_68c9948f67be1',
					'label' => 'Horario',
					'name' => 'opening_hours',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => 5,
					'placeholder' => 'D-X: 8:00 – 0:30 J: 8:00 – 1:00 V-S: 8:00 – 2:00',
					'new_lines' => 'wpautop',
				),
				array(
					'key' => 'field_68c9948f67be2',
					'label' => 'DJ\'s & Program',
					'name' => 'url_djs_program',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_68c9a0999e4a0',
					'label' => 'Reserva',
					'name' => 'url_booking',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'details-and-files',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );

add_action( 'acf/init', function() {
	acf_add_options_page( array(
	'page_title' => 'Fichas y enlaces',
	'menu_slug' => 'details-and-files',
	'parent_slug' => 'restaurants',
	'position' => '',
	'redirect' => false,
) );

	acf_add_options_page( array(
	'page_title' => 'Restaurantes',
	'menu_slug' => 'restaurants',
	'position' => 20,
	'redirect' => true,
	'menu_icon' => array(
		'type' => 'dashicons',
		'value' => 'dashicons-admin-multisite',
	),
	'icon_url' => 'dashicons-admin-multisite',
) );
} );

